{
 "title": "ML Sentiment App",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Request rate",
   "type": "timeseries",
   "description": "Request rate",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(prediction_requests_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate (5xx)",
   "type": "timeseries",
   "description": "Error rate (5xx)",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "rate(prediction_requests_total{status=~\"5..\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency p50/p95/p99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(prediction_request_duration_seconds_bucket[5m]))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, rate(prediction_request_duration_seconds_bucket[5m]))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, rate(prediction_request_duration_seconds_bucket[5m]))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "CPU/Memory per pod",
   "type": "timeseries",
   "description": "CPU/Memory per pod",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"ml-sentiment-app.*\"}[5m])",
     "legendFormat": "CPU {{pod}}"
    },
    {
     "expr": "container_memory_usage_bytes{pod=~\"ml-sentiment-app.*\"}",
     "legendFormat": "Memory {{pod}}"
    }
   ]
  }
 ]
}